title: Codemaxxer Blogs
description: "The Codemaxxer Blog!!!"
owner_name: Rachit Jaiswal
github_username: rachit-j
baseurl: "/codemaxxerblog"
remote_theme: jekyll/minima
#remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme
future: true
